apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MONGO_HOSTNAME: "mongodb-standalone-0.database.default.svc.cluster.local"  
  MONGO_PORT: "27017"
  MONGO_DB: "training"
